import type { Metadata } from "next";
import "../styles/globals.css";
import { Kanit } from "next/font/google";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Navbar from "@/components/navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const kanit = Kanit({
  weight: ["200", "400", "600", "800"],
  subsets: ["latin", "thai"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.className}`}>
        <Navbar />
        <AntdRegistry>
          <div className="flex flex-col min-h-dvh pt-12 z-0">{children}</div>
        </AntdRegistry>
      </body>
    </html>
  );
}
