import type { Metadata } from "next";
import "../styles/globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import Navbar from "@/components/layout/navbar";
import { ConfigProvider } from "antd";
import { antTheme } from "@/config/theme";

export const metadata: Metadata = {
  title: "CosBaanDeawGun",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-Kanit">
        <ConfigProvider theme={antTheme}>
          <AntdRegistry>
            <Navbar />
            <div className="flex flex-col min-h-dvh pt-16 z-0">{children}</div>
          </AntdRegistry>
        </ConfigProvider>
      </body>
    </html>
  );
}
